half2:
	 gcc cpy-conc-loc.c dec2n-convn.c buf-gets.c read-getl.c handl-genv.c rmenv-stenv.c init-free.c hist-CA.c rhist-bhist.c renhist-addnode.c adnend-prtlstr.c delnd-freelist.c linklen-rollstr.c prtlist-nodstrt.c getndind-entry.c free-iscmd.c dupch-fndpath.c memst-free.c realloc.c -half2

